routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	$item = App\Setting::first();
    return view('admin.login',compact('item'));
});

Route::get('signup', function () {
    return view('admin.login');
});

Route::get('index', function () {
	$slider= view('frontend.slider');
	$video= view('frontend.video');
	$main= view('frontend.main');
    return view('frontend.index',compact('slider','video','main'));
});

Route::get('join-us', function () {
    return view('frontend.login');
});

Route::get('sign-in', function () {
    return view('frontend.register');
});


Auth::routes();
Route::middleware(['auth'])->group(function () {
Route::get('home', 'BackendViewController@index')->name('home');
Route::resource('menu', 'MenuController');
Route::resource('role', 'RoleController');
Route::resource('setting', 'SettingController');
// Route::resource('media', 'MediaController');
Route::resource('user', 'UserController');
Route::resource('permission', 'PermissionController');
Route::get('get-permission', 'PermissionController@permission')->name('get-permission');
Route::resource('currency', 'CurrencyController');
Route::resource('company', 'CompanyController');
Route::resource('customer', 'CustomerController');
Route::resource('supplier', 'SupplierController');
Route::resource('bank', 'BankController');
Route::resource('tree', 'TreeController');
Route::get('list', 'TreeController@list');
Route::get('category-tree-view',['uses'=>'CategoryController@manageCategory'])->name('category-tree-view');
Route::post('add-category',['as'=>'add.category','uses'=>'CategoryController@addCategory']);
Route::resource('ledger', 'LedgerController');
Route::resource('purchase', 'PurchaseController');
Route::get('purch-pdf/{purch_id}', 'PurchaseController@pdf');
Route::resource('payment', 'PaymentController');
Route::resource('payment_type', 'PaymentTypeController');
Route::resource('invoice', 'InvoiceController');
Route::resource('receive', 'ReceiveVoucherController');
Route::resource('journal', 'JournalController');
//Route For the Report
Route::get('report', 'ReportController@report')->name('report');
Route::get('receive_paym', 'ReceivePaymentController@index')->name('receive_paym');
Route::post('receive_paym_post', 'ReceivePaymentController@store')->name('receive_paym_post');
Route::get('bank_book', 'BankController@report')->name('bank_book');
Route::post('bank_book_post', 'BankController@bankReport')->name('bank_book_post');
Route::get('group_index', 'GroupSummaryController@index')->name('group_index');
Route::post('group_post', 'GroupSummaryController@groupPost')->name('group_post');
Route::get('day_book_index', 'DayBookController@index')->name('day_book_index');
Route::post('day_book_post', 'DayBookController@store')->name('day_book_post');
Route::get('balance', 'BalanceController@index')->name('balance');
Route::post('balance_post', 'BalanceController@store')->name('balance_post');
});

app/Supplier.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Supplier extends Model
{
  protected $fillable = ['supplier','address','eamil','sup_id','currency','phone','image','under'];

  function getUser()
    {
      return $this->hasOne('App\User','id','created_by');
    }

    function getCurrency()
    {
      return $this->belongsTo('App\Currency','currency');
    } 
    
    function getUnder()
    {
      return $this->belongsTo('App\Category','under');
    } 
}

app/Http/Controllers/SupplierController.php
<?php

namespace App\Http\Controllers;

use App\Currency;
use App\Supplier;
use App\Category;
use Auth;
use Image;
use Redirect;
use Carbon\Carbon;
use Illuminate\Http\Request;

class SupplierController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $sups = Supplier::all();  
      return view('admin.supplier.index', compact('sups'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      $ledgers = Category::all();
      $curr = Currency::all();
      return view('admin.supplier.create', compact('curr','ledgers'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // print_r($request->all());

        $request->validate([
          'supplier' => 'required',
          'address' => 'required',
          'eamil' => 'required',
          'sup_id' => 'required|unique:suppliers,sup_id',
          'currency' => 'required',
          'image' => 'required',
          'under' => 'required',
          'phone' => 'required',
        ]);

        if($request->hasFile('image')){
          $image = $request->file('image');
          $filename = time() . '.' . $image->getClientOriginalExtension();
          Image::make($image)->save( public_path('Supplier/' . $filename ) );
        };

        Supplier::insert([
          'supplier' => $request->supplier,
          'address' => $request->address,
          'eamil' => $request->eamil,
          'sup_id' => $request->sup_id,
          'currency' => $request->currency,
          'image' => $filename,
          'phone' => $request->phone,
          'under' => $request->under,
          'created_by' => Auth::id(),
          'created_at' => Carbon::now(),
        ]);

          return redirect('supplier')->with('success', 'Supplier Add Successfully !!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Supplier  $supplier
     * @return \Illuminate\Http\Response
     */
    public function show(Supplier $supplier)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Supplier  $supplier
     * @return \Illuminate\Http\Response
     */
    public function edit($sup_id)
    {
      $ledgers = Category::all();
      $supp = Supplier::findOrFail($sup_id);
      $curr = Currency::all(); 
      return view('admin.supplier.edit' , compact('supp','curr','ledgers'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Supplier  $supplier
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $supp_id)
    {

      $request->validate([
        'supplier' => 'required',
        'address' => 'required',
        'eamil' => 'required',
        // 'sup_id' => 'required|unique:suppliers,sup_id',
        'currency' => 'required',
        'phone' => 'required',
      ]);


      $sup = Supplier::find($supp_id);

      if($request->hasFile('image')){
        $image = $request->file('image');
        $filename = time() . '.' . $image->getClientOriginalExtension();
        Image::make($image)->save( public_path('Supplier/' . $filename ) );
        $sup->image = $filename;
        $sup->save();
      };

      $sup->supplier = $request->supplier;
      $sup->address = $request->address;
      $sup->phone = $request->phone;
      $sup->eamil = $request->eamil;
      $sup->currency = $request->currency;
      $sup->under = $request->under;
      $sup->created_by = Auth::id();
      $sup->created_at = Carbon::now();
      $sup->save();

        // Supplier::find($supp_id)->update($request->all());
        return redirect('supplier')->with('succes', 'Supplier Update Successfully !!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Supplier  $supplier
     * @return \Illuminate\Http\Response
     */
    public function destroy($sup_id)
    {
        Supplier::where('id','=',$sup_id)->delete();
        return redirect('supplier')->with('succes', 'Supplier Delete Successfully !!');
    }
}

resources/views/admin/supplier/create.blade.php
@extends('admin.pages.dashboard')
@section('content')
<div class="wrapper-md">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading font-bold">
        <div class="row">
          <div class="col-md-10">
            <p class="m-n font-thin h3 text-primary"><i class="fa fa-folder-open"></i>&nbspCreate New Supplier</p>
          </div>
          <div class="col-md-2">
            <a href="{{route('supplier.index')}}" class="btn btn-info btn-sm">
                <i class="fa fa-list-ul"></i>&nbsp;&nbsp;All Supplier</a>
          </div>
        </div>
      </div>

      <div class="panel-body">
        @if ($errors->any())
            <div class="alert alert-danger">
              <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
              </ul>
            </div>
          @endif
          <form class="well form-horizontal" action="{{ route('supplier.store') }}" method="post" enctype="multipart/form-data">
            @csrf
            <div class="row">
              <div class="col-sm-5">
                <legend></legend>
     
                <div class="form-group">
                  <label class="col-md-4 control-label">{{ 'Supplier Name' }} <span style="color:red;">*</span></label>
                   <div class="col-md-8 inputGroupContainer">
                      <div class="input-group"><span class="input-group-addon"><i class="fa fa-suitcase"></i></span>
                        <input name="supplier" placeholder="Mr. Alex" class="form-control" required="true" value="{{ old('supplier') }}" type="text">
                      </div>
                   </div>
                </div>
                <div class="form-group">
                  <label class="col-md-4 control-label">{{ 'Supp ID' }} <span style="color:red;">*</span></label>
                   <div class="col-md-8 inputGroupContainer">
                      <div class="input-group"><span class="input-group-addon"><i class="fa fa-plus-square"></i></span>
                        <input name="sup_id" placeholder="Supplier ID" class="form-control" required="true" value="{{ old('sup_id') }}" type="text"></div>
                   </div>
                </div>
                <div class="form-group">
                  <label class="col-md-4 control-label">{{ 'Address' }} <span style="color:red;">*</span></label>
                   <div class="col-md-8 inputGroupContainer">
                      <div class="input-group"><span class="input-group-addon"><i class="fa fa-location-arrow"></i></span>
                        <input name="address" placeholder="74/C, Road No: 14" class="form-control" required="true" value="{{ old('address') }}" type="text">
                      </div>
                   </div>
                </div>
                <div class="form-group">
                  <label class="col-md-4 control-label">{{ 'Email' }} <span style="color:red;">*</span></label>
                   <div class="col-md-8 inputGroupContainer">
                      <div class="input-group"><span class="input-group-addon"><i class="fa fa-envelope"></i></span>
                        <input name="eamil" placeholder="name@gmail.com" class="form-control" required="true" value="{{ old('eamil') }}" type="email">
                      </div>
                   </div>
                </div>
                {{-- <div class="form-group">
                  <label class="col-md-4 control-label">{{ 'Website' }} <span style="color:red;">*</span></label>
                   <div class="col-md-8 inputGroupContainer">
                      <div class="input-group"><span class="input-group-addon"><i class="fa fa-globe"></i></span>
                        <input id="fullName" name="website" placeholder="www.test.com" class="form-control" required="true" value="{{ old('website') }}" type="text"></div>
                   </div>
                </div> --}}
              </div>
              <div class="col-sm-5">
                <legend></legend>
                <div class="form-group">
                  <label class="col-md-4 control-label">{{ 'Photo' }} <span style="color:red;">*</span></label>
                   <div class="col-md-8 inputGroupContainer">
                      <div class="input-group"><span class="input-group-addon"><i class="fa fa-file-powerpoint-o"></i></span>
                        <input name="image" placeholder="Supplier ID" class="form-control" required="true" value="{{ old('image') }}" type="file"></div>
                   </div>
                </div>
                <div class="form-group">
                  <label class="col-md-4 control-label">Currency</label>
                  <div class="col-md-8 inputGroupContainer">
                      <div class="input-group">
                        <span class="input-group-addon" style="max-width: 100%;"><i class="fa fa-money" aria-hidden="true"></i></span>
                        <select class="form-control" value="{{ old('currency') }}" required="true" name="currency">
                          <option value=" ">-- Select One--</option>
                          @if(!empty($curr))
                          @foreach($curr as $cur)
                          <option value="{{ $cur->id }}">{{ $cur->code }}</option>
                          @endforeach
                          @endif
                        </select>
                      </div>
                  </div>
                </div>
                {{-- <div class="form-group">
                  <label class="col-md-4 control-label">{{ 'Under' }}</label>
                  <div class="col-md-8 inputGroupContainer">
                      <div class="input-group">
                        <span class="input-group-addon" style="max-width: 100%;"><i class="fa fa-shield" aria-hidden="true"></i></span>
                        <select class="form-control under" value="{{ old('under') }}" required="true" id="under" name="under">
                          <option value="">Select One</option>
                          @if(!empty($ledgers))
                          @foreach($ledgers as $item)
                          <option data-tokens="{{ $item->title }}" value="{{ $item->id }}">{{ $item->title }}</option>
                          @php $sub=DB::table('categories')->where('parent_id',$item->id)->get(); @endphp
                          @foreach($sub as $it)
                          <option value="{{$it->id}}">&nbsp;&nbsp;&nbsp;&nbsp;{{$it->title}} </option>
                          @php $child=DB::table('categories')->where('parent_id',$it->id)->get(); @endphp
                          @foreach($child as $child)
                          <option value="{{$child->id}}">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{$child->title}} </option>
                          @endforeach
                          @endforeach
                          @endforeach
                          @endif
                        </select>
                      </div>
                  </div>
                </div> --}}
                <div class="form-group">
                  <label class="col-md-4 control-label">{{ 'Phone' }} <span style="color:red;">*</span></label>
                   <div class="col-md-8 inputGroupContainer">
                      <div class="input-group"><span class="input-group-addon"><i class="fa fa-phone"></i></span>
                        <input name="phone" placeholder="01521470000" class="form-control" required="true" value="{{ old('phone') }}" type="number"></div>
                   </div>
                </div>

              </div>
            </div>
           <br>
            <button type="submit" class="btn btn-primary center-block fa fa-paper-plane">&nbspSubmit</button>
          </form>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/admin/supplier/edit.blade.php
@extends('admin.pages.dashboard')
@section('content')
<div class="wrapper-md">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading font-bold">
        <div class="row">
          <div class="col-md-10">
            <p class="m-n font-thin h3 text-primary"><i class="fa fa-pencil-square-o"></i>&nbspEdit New Supplier</p>
          </div>
          <div class="col-md-2">
            <a href="{{route('supplier.index')}}" class="btn btn-info btn-sm">
                <i class="fa fa-list-ul"></i>&nbsp;&nbsp;All Supplier</a>
          </div>
        </div>
      </div>

      <div class="panel-body">
        @if ($errors->any())
            <div class="alert alert-danger">
              <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
              </ul>
            </div>
          @endif
          <form class="well form-horizontal" action="{{ route('supplier.update', $supp->id) }}" method="post" enctype="multipart/form-data">
            @csrf
            <input type="hidden" name="_method" value="PUT" />
            <div class="row">
              <div class="col-sm-5">
                <legend></legend>
     
                <div class="form-group">
                  <label class="col-md-4 control-label">{{ 'Supplier Name' }} <span style="color:red;">*</span></label>
                   <div class="col-md-8 inputGroupContainer">
                      <div class="input-group"><span class="input-group-addon"><i class="fa fa-suitcase"></i></span>
                        <input name="supplier" placeholder="Mr. Alex" class="form-control" required="true" value="{{ $supp->supplier }}" type="text">
                      </div>
                   </div>
                </div>
                <div class="form-group">
                  <label class="col-md-4 control-label">{{ 'Under' }}</label>
                  <div class="col-md-8 inputGroupContainer">
                      <div class="input-group">
                        <span class="input-group-addon" style="max-width: 100%;"><i class="fa fa-shield" aria-hidden="true"></i></span>
                        <select class="form-control" value="{{ old('under') }}" required="true" name="under">
                          @if(!empty($ledgers))
                          @foreach($ledgers as $ledger)
                          <option value="{{ $ledger->id }}" <?php if($ledger->id == $supp->under) {echo"selected";} ?> >{{ $ledger->title }}-{{ $ledger->id }}</option>
                          @endforeach
                          @endif
                        </select>
                      </div>
                  </div>
                </div>
                <div class="form-group">
                  <label class="col-md-4 control-label">{{ 'Address' }} <span style="color:red;">*</span></label>
                   <div class="col-md-8 inputGroupContainer">
                      <div class="input-group"><span class="input-group-addon"><i class="fa fa-location-arrow"></i></span>
                        <input name="address" placeholder="74/C, Road No: 14" class="form-control" required="true" value="{{ $supp->address }}" type="text">
                      </div>
                   </div>
                </div>
                <div class="form-group">
                  <label class="col-md-4 control-label">{{ 'Email' }} <span style="color:red;">*</span></label>
                   <div class="col-md-8 inputGroupContainer">
                      <div class="input-group"><span class="input-group-addon"><i class="fa fa-envelope"></i></span>
                        <input name="eamil" placeholder="name@gmail.com" class="form-control" required="true" value="{{ $supp->eamil }}" type="email">
                      </div>
                   </div>
                </div>
                {{-- <div class="form-group">
                  <label class="col-md-4 control-label">{{ 'Website' }} <span style="color:red;">*</span></label>
                   <div class="col-md-8 inputGroupContainer">
                      <div class="input-group"><span class="input-group-addon"><i class="fa fa-globe"></i></span>
                        <input id="fullName" name="website" placeholder="www.test.com" class="form-control" required="true" value="{{ old('website') }}" type="text"></div>
                   </div>
                </div> --}}
              </div>
              <div class="col-sm-5">
                <legend></legend>
                <div class="form-group">
                  <label class="col-md-4 control-label">{{ 'Photo' }} <span style="color:red;">*</span></label>
                   <div class="col-md-8 inputGroupContainer">
                      <div class="input-group"><span class="input-group-addon"><i class="fa fa-file-powerpoint-o"></i></span>
                        <input name="image" placeholder="Supplier ID" class="form-control" value="{{ $supp->image }}" type="file"></div>
                   </div>
                </div>
                <div class="form-group">
                  <label class="col-md-4 control-label">Currency</label>
                  <div class="col-md-8 inputGroupContainer">
                      <div class="input-group">
                        <span class="input-group-addon" style="max-width: 100%;"><i class="fa fa-money" aria-hidden="true"></i></span>
                        <select class="form-control" value="{{ old('currency') }}" required="true" name="currency">
                          <option value=" ">-- Select One--</option>
                          @if(!empty($curr))
                          @foreach($curr as $cur)
                          <option value="{{ $cur->id }}" <?php if($cur->id == $supp->currency) {echo"selected";} ?> >{{ $cur->code }}</option>
                          @endforeach
                          @endif
                        </select>
                      </div>
                  </div>
                </div>
                <div class="form-group">
                  <label class="col-md-4 control-label">{{ 'Phone' }} <span style="color:red;">*</span></label>
                   <div class="col-md-8 inputGroupContainer">
                      <div class="input-group"><span class="input-group-addon"><i class="fa fa-phone"></i></span>
                        <input name="phone" placeholder="01521470000" class="form-control" required="true" value="{{ $supp->phone }}" type="number"></div>
                   </div>
                </div>

              </div>
            </div>
           <br>
            <button type="submit" class="btn btn-primary center-block fa fa-paper-plane">&nbspUpdate</button>
          </form>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/admin/supplier/index.blade.php
@extends('admin.pages.dashboard')
 @section('content')
 {{-- <style type="text/css">
  .fa{
    font-size: 14px;
  }
 </style> --}}
<div class="wrapper-md">
  <div class="panel panel-default">
    <div class="panel-heading">
      <div class="row">
        <div class="col-md-10">
          <p class="m-n font-thin h3 text-primary"><i class="fa fa-share-alt-square"></i> &nbspSupplier</p>
        </div>
        <div class="col-md-2">
          <a style="font-size: 14px;" href="{{ route('supplier.create') }}" class="btn btn-primary btn-sm"><i
              class="fa fa-plus"></i>&nbsp;Add New Supplier</a>
        </div>
     </div>
   </div>
    <div class="panel-body">
      <table id="pattern-type-data" class="table table-bordered text-center">
        <thead>
        <tr>
          <th class="text-center">SL</th>
          <th class="text-center">Image</th>
          <th class="text-center">Name</th>
          <th class="text-center">Id</th>
          <th class="text-center">Email</th>
          <th class="text-center">Phone</th>
          <th class="text-center">Currency</th>
          <th class="text-center">Under</th>
          <th class="text-center">Address</th>
          <th class="text-center">Created By</th>
          <th class="text-center">Actions</th>
        </tr>
        </thead>
        <tbody>
          <?php $a=1; ?>
          @forelse ($sups as $sup)
          <tr>
            <td>{{ $a++ }}</td>
            <td> <img class="img-profile rounded-circle" width="70" height="40" src="{{ asset('public/Supplier/'. $sup->image ) }}" alt="Photo Not Found"> </td>
            <td>{{ $sup->supplier }}</td>
            <td>{{ $sup->sup_id }}</td>
            <td>{{ $sup->eamil }}</td>
            <td>{{ $sup->phone }}</td>
            <td>{{ $sup->getCurrency->code }}</td>
            <td>{{ $sup->getUnder->title }}</td>
            <td>{{ $sup->address }}</td>
            <td>{{ $sup->getUser->name }}</td>
            <td>
              <form action="{{ route('supplier.destroy',$sup->id) }}" method="POST">
                <button type="button" data-toggle="tooltip" data-placement="top" title='Edit' class=" btn btn-sm btn-success edit_link"
                value="{{ route('supplier.edit',$sup->id) }}" ><i class="fa fa-pencil"> </i></button>
                @csrf
                @method('DELETE')
                {{-- <button type="submit" data-toggle="tooltip" data-placement="top" title='Delete' class=" btn btn-sm btn-success" onclick="return confirm('Are you sure you want to Delete ?');" ><i class="fa fa-trash"> </i></button> --}}
              </form>
            </td>
          </tr>
          @empty
          <tr>
          <td colspan="12" class="text-center"><h2>No Supplier Here</h2></td>
        </tr>
          @endforelse
        </tbody>
      </table>
    </div>
  </div>
</div>

@endsection