routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	$item = App\Setting::first();
    return view('admin.login',compact('item'));
});

Route::get('signup', function () {
    return view('admin.login');
});

Route::get('index', function () {
	$slider= view('frontend.slider');
	$video= view('frontend.video');
	$main= view('frontend.main');
    return view('frontend.index',compact('slider','video','main'));
});

Route::get('join-us', function () {
    return view('frontend.login');
});

Route::get('sign-in', function () {
    return view('frontend.register');
});


Auth::routes();
Route::middleware(['auth'])->group(function () {
Route::get('home', 'BackendViewController@index')->name('home');
Route::resource('menu', 'MenuController');
Route::resource('role', 'RoleController');
Route::resource('setting', 'SettingController');
// Route::resource('media', 'MediaController');
Route::resource('user', 'UserController');
Route::resource('permission', 'PermissionController');
Route::get('get-permission', 'PermissionController@permission')->name('get-permission');
Route::resource('currency', 'CurrencyController');
Route::resource('company', 'CompanyController');
Route::resource('customer', 'CustomerController');
Route::resource('supplier', 'SupplierController');
Route::resource('bank', 'BankController');
Route::resource('tree', 'TreeController');
Route::get('list', 'TreeController@list');
Route::get('category-tree-view',['uses'=>'CategoryController@manageCategory'])->name('category-tree-view');
Route::post('add-category',['as'=>'add.category','uses'=>'CategoryController@addCategory']);
Route::resource('ledger', 'LedgerController');
Route::resource('purchase', 'PurchaseController');
Route::get('purch-pdf/{purch_id}', 'PurchaseController@pdf');
Route::resource('payment', 'PaymentController');
Route::resource('payment_type', 'PaymentTypeController');
Route::resource('invoice', 'InvoiceController');
Route::resource('receive', 'ReceiveVoucherController');
Route::resource('journal', 'JournalController');
//Route For the Report
Route::get('report', 'ReportController@report')->name('report');
Route::get('receive_paym', 'ReceivePaymentController@index')->name('receive_paym');
Route::post('receive_paym_post', 'ReceivePaymentController@store')->name('receive_paym_post');
Route::get('bank_book', 'BankController@report')->name('bank_book');
Route::post('bank_book_post', 'BankController@bankReport')->name('bank_book_post');
Route::get('group_index', 'GroupSummaryController@index')->name('group_index');
Route::post('group_post', 'GroupSummaryController@groupPost')->name('group_post');
Route::get('day_book_index', 'DayBookController@index')->name('day_book_index');
Route::post('day_book_post', 'DayBookController@store')->name('day_book_post');
Route::get('balance', 'BalanceController@index')->name('balance');
Route::post('balance_post', 'BalanceController@store')->name('balance_post');
});

app/Purchase.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Purchase extends Model
{
  protected $fillable = ['purchase_no','party_name','bank_acc','note','date','under','item_name','quantity','rate','total'];

  function getUser()
    {
      return $this->hasOne('App\User','id','created_by');
    }

  function getBank()
    {
      return $this->belongsTo('App\Bank','bank_acc');
    }

  function getParty()
    {
      return $this->belongsTo('App\Supplier','party_name');
    }

    function getUnder()
    {
      return $this->belongsTo('App\Category','under');
    } 

    function getProduct()
    {
      return $this->hasMany('App\Product','purch_id','id');
    } 

    function tr()
    {
      return $this->belongsTo('App\Category','item_name');
    } 

 
}

app/Http/Controllers/PurchaseController.php
<?php

namespace App\Http\Controllers;

use App\Bank;
use App\Category;
use App\Product;
use App\Purchase;
use App\Supplier;
use Carbon\Carbon;
use Image;
use PDF;
use App\Setting;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class PurchaseController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $sl = 1;
      $ledgers = Category::all();
      $purches = Purchase::with(['tr','tr.chil'])->get();  
      return view('admin.purchase.index', compact('purches','ledgers','sl'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      $ledgers = Category::all();
      $supp = Supplier::all();
      $bank = Bank::all();
      return view('admin.purchase.create', compact('supp','bank','ledgers'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $request->validate([
          'purchase_no' => 'required|unique:purchases,purchase_no',
          'party_name' => 'required',
          'bank_acc' => 'required',
          'note' => 'required',
          'date' => 'required',
          'under' => 'required',
          'item_name' => 'required',
          'quantity' => 'required',
          'rate' => 'required',
          'reference_no' => 'required',
        ]);

        $filename = NULL;
        if($request->hasFile('att_file')){
          $file = $request->file('att_file'); 
          $filename = time() . '.' . $file->getClientOriginalExtension();
          Image::make($file)->save( public_path('Purchase/' . $filename ) );
        }
        $purchs = Purchase::insertGetId([
          'purchase_no' => $request->purchase_no,
          'party_name' => $request->party_name,
          'bank_acc' => $request->bank_acc,
          'note' => $request->note,
          'date' => $request->date,
          'under' => $request->under,
          'item_name' => $request->item_name,
          'quantity' => $request->quantity,
          'rate' => $request->rate,
          'total' => $request->rate*$request->quantity,
          'reference_no' => $request->reference_no,
          'file' => $filename,
          'created_by' => Auth::id(),
          'created_at' => Carbon::now(),
        ]);

      //   $i = 0;
      //   foreach ($request->item_name as $i => $product_name) {
      //     // $categ_info = Category::create([
      //     //   'parent_id' => $request->under,
      //     //   'title' => $product_name, 
      //     // ]);
        
      //   $prod = Product::create([
      //     'purch_id' => $purchs,
      //     'bank_acc' => $request->bank_acc,
      //     'item_name' => $request->item_name[$i],
      //     'rate' => $request->rate[$i],
      //     'quantity' => $request->quantity[$i],
      //     'total' => $request->rate[$i]*$request->quantity[$i],
      //     'created_by' => Auth::id(),
      //     'created_at' => Carbon::now(),
      //   ]);

      // }

        return redirect('purchase')->with('success','Purchase Voucher Add Successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Purchase  $purchase
     * @return \Illuminate\Http\Response
     */
    public function show($purch_id)
    {
        $imga = Purchase::findOrfail($purch_id);
        return view('admin.purchase.view', compact('imga') );
    }

    public function pdf($purch_id)
    {
      $sl = 1;
      $setting = Setting::first();
      $purchase = Purchase::findOrfail($purch_id);
      // dd($purchase);
      $total = Product::where('purch_id',$purchase->id)->sum('total');
      $quant = Product::where('purch_id',$purchase->id)->sum('quantity');
      $pdf = PDF::loadView('admin.purchase.pdf', compact('purchase','setting','sl','total','quant'))->setPaper('a4');
      return $pdf->stream('purchase.pdf');
      // return $pdf->download('purchase.pdf');

      // return view('admin.purchase.pdf', compact('purchase','setting'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Purchase  $purchase
     * @return \Illuminate\Http\Response
     */
    public function edit($purch_id)
    {
      $ledgers = Category::all();
      $supp = Supplier::all();
      $bank = Bank::all();
      $purch = Purchase::findOrFail($purch_id);  
      return view('admin.purchase.edit', compact('supp','bank','purch','ledgers'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Purchase  $purchase
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $purch_id)
    {

      $purc = Purchase::find($purch_id);

      $request->validate([
        'party_name' => 'required',
        'bank_acc' => 'required',
        'note' => 'required',
        'date' => 'required',
        'under' => 'required',
        'item_name' => 'required',
        'quantity' => 'required',
        'rate' => 'required',
        'reference_no' => 'required',
      ]);


      if($request->hasFile('att_file')){
          
        if ($purc->file){
          unlink(public_path('Purchase/' . $purc->file) );
      }
        $file = $request->file('att_file');
        $filename = time() . '.' . $file->getClientOriginalExtension();
        Image::make($file)->save( public_path('Purchase/' . $filename ) );
        $purc->file = $filename;
        $purc->save();
      }

      $categ = Category::find($request->item_name_id)->update([
        'title'=> $request->item_name, 
        'parent_id'=> $request->under
        ]);

        $purc->party_name = $request->party_name;
        $purc->bank_acc = $request->bank_acc;
        $purc->note = $request->note;
        $purc->date = $request->date;
        $purc->quantity = $request->quantity;
        $purc->rate = $request->rate;
        $purc->total = $request->quantity*$request->rate;
        $purc->reference_no = $request->reference_no;
        $purc->created_by = Auth::id();
        $purc->created_at = Carbon::now();
        $purc->save();

        return redirect('purchase')->with('success', 'purchase Update Successfully !');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Purchase  $purchase
     * @return \Illuminate\Http\Response
     */
    public function destroy($purch_id)
    {
      Purchase::where('id','=',$purch_id)->delete();
      return redirect('purchase')->with('succes', 'Purchase Delete Successfully !!');
    }
}

resources/views/admin/purchase/create.blade.php
@extends('admin.pages.dashboard')
@section('content')

<div class="wrapper-md">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading font-bold">
        <div class="row">
          <div class="col-md-10">
            <p class="m-n font-thin h3 text-primary"><i class="fa fa-folder-open"></i>&nbsp Create New Purchase Order</p>
          </div>
          <div class="col-md-2">
            <a href="{{route('purchase.index')}}" class="btn btn-info btn-sm">
                <i class="fa fa-list-ul"></i>&nbsp;&nbsp;All Voucher</a>
          </div>
        </div>
      </div>

      <div class="panel-body">
        @if ($errors->any())
            <div class="alert alert-danger">
              <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
              </ul>
            </div>
          @endif
          <form class="well form-horizontal" action="{{ route('purchase.store') }}" method="post" enctype="multipart/form-data">
            @csrf
            <div class="row">
              <div class="col-sm-5">
                <legend></legend>
                <div class="form-group">
                  <label class="col-md-4 control-label">{{ 'Purchase No' }} <span style="color:red;">*</span></label>
                   <div class="col-md-8 inputGroupContainer">
                      <div class="input-group"><span class="input-group-addon"><i class="fa fa-plus-square"></i></span>
                        <input name="purchase_no" placeholder="2345" class="form-control" required="true" value="{{ old('purchase_no') }}" type="text">
                      </div>
                   </div>
                </div>
                <div class="form-group">
                  <label class="col-md-4 control-label">{{ 'Party A/C Name' }} <span style="color:red;">*</span></label>
                  <div class="col-md-8 inputGroupContainer">
                      <div class="input-group">
                        <span class="input-group-addon" style="max-width: 100%;"><i class="fa fa-shield" aria-hidden="true"></i></span>
                        <select class="form-control" value="" required="true" name="party_name">
                          <option value=" ">-- Select One--</option>
                          @if(!empty($supp))
                          @foreach($supp as $sup)
                          <option value="{{ $sup->id }}">{{ $sup->supplier }}-{{ $sup->sup_id }}</option>
                          @endforeach
                          @endif
                        </select>
                      </div>
                  </div>
                </div>
                <div class="form-group">
                  <label class="col-md-4 control-label">{{ 'Bank Acc' }}</label>
                  <div class="col-md-8 inputGroupContainer">
                      <div class="input-group">
                        <span class="input-group-addon" style="max-width: 100%;"><i class="fa fa-money" aria-hidden="true"></i></span>
                        <select class="form-control" value="{{ old('bank_acc') }}" required="true" id="bank_acc" name="bank_acc">
                          <option value=" ">-- Select One--</option>
                          @if(!empty($bank))
                          @foreach($bank as $ban)
                          <option value="{{ $ban->id }}">{{ $ban->bank_name }}</option>
                          @endforeach
                          @endif
                        </select>
                      </div>
                  </div>
                </div>

                <div class="form-group">
                  <label class="col-md-4 control-label">{{ 'File' }}</label>
                   <div class="col-md-8 inputGroupContainer">
                      <div class="input-group"><span class="input-group-addon"><i class="fa fa-file-photo-o"></i></span>
                        <input name="att_file" placeholder="500" class="form-control"value="{{ old('att_file') }}" type="file">
                      </div>
                   </div>
                </div>
                <div class="form-group">
                  <label class="col-md-4 control-label">{{ 'Description' }}</label>
                  <div class="col-md-8 inputGroupContainer">
                      <div class="input-group"><span class="input-group-addon"><i class="fa fa-globe"></i></span>
                        <textarea rows="3" cols="30" name="note">{{ old('note') }}</textarea>
                      </div>
                  </div>
                </div>
              </div>
              <div class="col-sm-5">
                <legend></legend>
                <div class="form-group">
                  <label class="col-md-4 control-label">{{ 'Date' }} <span style="color:red;">*</span></label>
                   <div class="col-md-8 inputGroupContainer">
                      <div class="input-group"><span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                        <input name="date" placeholder="Customer ID" class="form-control" required="true" value="{{ old('date') }}" type="date"></div>
                   </div>
                </div>
                <div class="form-group">
                  <label class="col-md-4 control-label">{{ 'Under' }} <span style="color:red;">*</span></label>
                  <div class="col-md-8 inputGroupContainer">
                      <div class="input-group">
                        <span class="input-group-addon" style="max-width: 100%;"><i class="fa fa-shield" aria-hidden="true"></i></span>
                        <select class="form-control" value="{{ old('under') }}" required="true" id="under" name="under">
                          <option value="">Select One</option>
                          @if(!empty($ledgers))
                          @foreach($ledgers as $item)
                          <option data-tokens="{{ $item->title }}" value="{{ $item->id }}">{{ $item->title }}</option>
                          <?php $sub=DB::table('categories')->where('parent_id',$item->id)->get(); ?>
                          @foreach($sub as $it)
                          <option value="{{$it->id}}">&nbsp;&nbsp;&nbsp;&nbsp;{{$it->title}} </option>
                          <?php $child=DB::table('categories')->where('parent_id',$it->id)->get(); ?>
                          @foreach($child as $child)
                          <option value="{{$child->id}}">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{$child->title}} </option>
                          @endforeach
                          @endforeach
                          @endforeach
                          @endif
                        </select>
                      </div>
                  </div>
                </div>
                
                <div class="form-group">
                  <label class="col-md-4 control-label">{{ 'Reference No' }} <span style="color:red;">*</span></label>
                   <div class="col-md-8 inputGroupContainer">
                      <div class="input-group"><span class="input-group-addon"><i class="fa fa-reorder"></i></span>
                        <input name="reference_no" placeholder="500" class="form-control" required="true" value="{{ old('reference_no') }}" type="text"></div>
                   </div>
                </div>

                <div class="form-group">
                  <label class="col-md-4 control-label">{{ 'Item Name' }} <span style="color:red;">*</span></label>
                   <div class="col-md-8 inputGroupContainer">
                      <div  class="input-group"><span class="input-group-addon"><i class="fa fa-cubes"></i></span>
                        <input  name="item_name" placeholder="Product Name" class="form-control" required="true" value="{{ old('item_name') }}" type="text"></div>
                   </div>
                </div>

                <div class="form-group">
                  <label class="col-md-4 control-label">{{ 'Rate(Per)' }} <span style="color:red;">*</span></label>
                   <div class="col-md-8 inputGroupContainer">
                      <div class="input-group"><span class="input-group-addon"><i class="fa fa-reorder"></i></span>
                        <input name="rate" placeholder="500" class="form-control" required="true" value="{{ old('rate') }}" type="number"></div>
                   </div>
                </div>

                <div class="form-group">
                  <label class="col-md-4 control-label">{{ 'Quantity' }} <span style="color:red;">*</span></label>
                   <div class="col-md-8 inputGroupContainer">
                      <div class="input-group"><span class="input-group-addon"><i class="fa fa-reorder"></i></span>
                        <input id="quantity" name="quantity" placeholder="10" class="form-control" required="true" value="{{ old('quantity') }}" type="number">
                      </div> 
                   </div>
                </div>

              </div>
            </div>
           <br>
            <button type="submit" class="btn btn-primary center-block fa fa-paper-plane">&nbspSubmit</button>
          </form>
      </div>
    </div>
  </div>
</div>

  @endsection

resources/views/admin/purchase/index.blade.php
@extends('admin.pages.dashboard')
 @section('content')
<div class="wrapper-md">
  <div class="panel panel-default">
    <div class="panel-heading">
      <div class="row">
        <div class="col-md-10">
          <p class="m-n font-thin h3 text-primary"><i class="fa fa-credit-card"></i> &nbspPurchase Order List</p>
        </div>
        <div class="col-md-2">
          <a style="font-size: 14px;" href="{{ route('purchase.create') }}" class="btn btn-primary btn-sm"><i
              class="fa fa-plus"></i>&nbsp;Add New Voucher</a>
        </div>
     </div>
   </div>
    <div class="panel-body">
      <table id="pattern-type-data" class="table table-bordered text-center">
        <thead>
        <tr>
          <th class="text-center">SL.</th>
          <th class="text-center">Pur No</th>
          <th class="text-center">Refer No</th>
          <th class="text-center">Party Acc</th>
          <th class="text-center">Bank Ac</th>
          <th class="text-center">Under</th>
          <th class="text-center">Description</th>
          {{-- <th class="text-center">Quantity</th>
          <th class="text-center">Price (Single)</th> --}}
          {{-- <th class="text-center">Total</th> --}}
          <th class="text-center">Date</th>
          <th class="text-center">Created By</th>
          <th class="text-center">Actions</th>
        </tr>
        </thead>
        <tbody>
          @forelse ($purches as $purch)
          <tr>
            <td>{{ $sl++ }}</td>
            <td style="width:10px;">{{ $purch->purchase_no }}</td>
            <td style="width:10px;">{{ $purch->reference_no }}</td>
            <td>{{ $purch->getParty->supplier }}</td>
            <td>{{ $purch->getBank->bank_name }}</td>
            <td>{{ $purch->getUnder->title }}</td>
            <td style="width:240px;">{{ $purch->note }}</td>
            <td>{{ $purch->date }}</td>
            <td style="width:10px;">{{ $purch->getUser->name }}</td>
            <td style="width:140px;">
              <form action="{{ route('purchase.destroy',$purch->id) }}" method="POST">
                <a href="{{ route('purchase.show',$purch->id) }}" data-toggle="tooltip" data-placement="top" title='Voucher Image' class=" btn btn-sm btn-info" target="_blank"><i class="fa fa-film" aria-hidden="true"></i></a>
                <button type="button" data-toggle="tooltip" data-placement="top" title='Edit' class=" btn btn-sm btn-success edit_link" value="{{ route('purchase.edit',$purch->id) }}" ><i class="fa fa-pencil"> </i></button>
                <a href="{{ url('purch-pdf') }}/{{ $purch->id }} " data-toggle="tooltip" data-placement="top" title='Make PDF' class=" btn btn-sm btn-warning" target="_blank"><i class="fa fa-file-pdf-o" aria-hidden="true"></i></a>
                @csrf
                @method('DELETE')
                {{-- <button type="submit" data-toggle="tooltip" data-placement="top" title='Delete' class=" btn btn-sm btn-success" onclick="return confirm('Are you sure you want to Delete ?');" ><i class="fa fa-trash"> </i></button> --}}
              </form>
            </td>
          </tr>
          @empty
          <tr>
          <td colspan="12" class="text-center"><h2>No Purches Here</h2></td>
        </tr>
          @endforelse
        </tbody>
      </table>
    </div>
  </div>
</div>

@endsection

resources/views/admin/purchase/pdf.blade.php
<!DOCTYPE html>
<html>
  <head>
    <title>Purchase Order</title>
    <style>

      div.b {
            line-height: 1.6;
            text-align: center;
          }

        .divLeft {
            width:500px;
            display:block;
            float: left;
          }
          .divRight {
            width:600px;
            display:block;
            float: right;
            padding-left: 450px;
          }
      table, td, th {  
        border: 1px solid #ddd;
        text-align: left;
      }
      th {  
        background-color:#b3ecff;
      }

      table {
        border-collapse: collapse;
        width: 100%;
      }

      th, td {
        padding: 10px;
      }

      .split {
      float: left;
      margin-right:220px;
      margin-bottom: 0px;
      }

      .row{
        padding-left: 45px;
      }


      .footer {
        position: fixed;
        text-align: center;
        left: 0;
        bottom: 0;
        width: 100%; 
      }

    </style>
  </head>
<body>

  <div class="b">
    <img src="{{ asset('public/CompLogo/'.$setting->getCompany->comp_logo) }}" class="img-responsive" /><br>
    {{ $setting->getCompany->company }} <br>
    {{ $setting->getCompany->address }}
  </div>

  <h3 style="text-align: center;" >Purchase Order</h3><br><br>
  
  <div class="divLeft">
   <p><b>Purchase No #</b>: {{ $purchase->purchase_no }}</p>
   <p><b>Party Name:</b> {{ $purchase->getParty->supplier }}</p>
   <p><b>Bank Account:</b> {{ $purchase->getBank->bank_name }}</p>
  </div>

  <div class="divRight">
    <p><b>Date :</b> {{ $purchase->date }}</p>
    <p><b>Reference NO :</b> {{ $purchase->reference_no }}</p>
    <p><b>Under :</b> {{ $purchase->getUnder->title }}</p>
  </div><br><br><br><br><br><br><br><br>
  <table>
    <tr>
      <th>SL</th>
      <th>Name of the Item</th>
      <th>Quantity</th>
      <th>Rate</th>
      <th>Amount</th>
    </tr>
    {{-- @foreach ($purchase as $item) --}}
    <tr>
      <td>{{ $sl++ }}</td>
      <td>{{ $purchase->item_name }}</td>
      <td>{{ $purchase->quantity }}</td>
      <td>{{ $purchase->rate }}</td>
      <td>{{ $purchase->total }}</td>
    </tr>
    {{-- @endforeach --}}
    <tr>
      <td colspan="2" ><i>Total :</i></td>
    <td colspan="" style="" >{{ $purchase->quantity }} </td>
      <td colspan="2" style="padding-left: 179px;"><b>{{ $purchase->total }}</b></td>
    </tr>
  </table>
  <p><b>Description :</b> {{ $purchase->note }}</p><br><br><br><br><br><br><br><br><br>
  
  <div class="row abc">
    <div class="split">
        <label style="" class="col-md-4 control-label">----------------<br><span class="sp">{{ 'Supplier' }} </span></label>
    </div>

    <div class="split">
        
    </div>

    <div class="cols">
        <div class="split">
            <label style="" class="col-md-4 control-label">----------------<br><span class="sp">{{ 'Authorised' }} </span></label>
        </div>
        <div class="split">
            
        </div>
    </div>
  </div>

  <div class="footer">
    <h1></h1>
    <p>{{ $setting->getCompany->copyright }}</p>
  </div>
</body>
</html>

resources/views/admin/purchase/pdf2.blade.php
<!DOCTYPE html>
<html>
  <head>
    <title>Purchase Order</title>
    <style>
    div.b {
      line-height: 1.6;
      text-align: center;
    }

  .divLeft {
      width:500px;
      display:block;
      float: left;
    }
    .divRight {
      width:600px;
      display:block;
      float: right;
      padding-left: 450px;
    }

    table, td, th {
      border: 1px solid black;
      text-align: center;
    }

    table {
      border-collapse: collapse;
      width: 100%;
    }

    th {
      height: 50px;
      /* text-align: center; */
    }
    .footer {
        position: fixed;
        text-align: center;
        left: 0;
        bottom: 0;
        width: 100%; 
      }
      
    .split {
    float: left;
    margin-right:220px;
    margin-bottom: 0px;
    }

      .row{
        padding-left: 45px;
    }

    </style>
  </head>
<body>

  <div class="b">
    <img src="{{ asset('public/CompLogo/'.$setting->getCompany->comp_logo) }}" class="img-responsive" /><br>
    {{ $setting->getCompany->company }} <br>
    {{ $setting->getCompany->address }}
  </div>

  <h3 style="text-align: center;" >Purchase Order</h3><br><br>
  
  <div class="divLeft">
   <p>Purchase No #: {{ $purchase->purchase_no }}</p>
   <p>Party Name: <b>{{ $purchase->getParty->supplier }}</b></p>
  </div>

  <div class="divRight">
    <p>Date : {{ $purchase->date }}</p>
    <p>Reference NO : {{ $purchase->reference_no }}</p>
  </div><br><br><br><br><br><br><br>
  
  <table>
    <tr>
      <th>SL #</th>
      <th>Name of the Item</th>
      <th>Quantity</th>
      <th>Rate</th>
      <th>Total</th>
    </tr>
    @foreach ($purchase->getProduct as $item)
    <tr>
      <td>{{ $sl++ }}</td>
      <td>{{ $item->item_name }}</td>
      <td>{{ $item->quantity }}</td>
      <td>{{ $item->rate }}</td>
      <td>{{ $item->total }}</td>
    </tr>
    @endforeach
    <tr>
      <td colspan="2" >Total :</td>
    <td colspan="" style="" >{{ $quant }} </td>
      <td colspan="2" style="padding-left: 179px;" >{{ $total}}</td>
    </tr>
  </table>
  <p><b>Note :</b> {{ $purchase->note }}</p><br><br><br><br><br><br><br><br><br>
  <div class="row abc">
      <div class="split">
          <label style="" class="col-md-4 control-label">----------------<br><span class="sp">{{ 'Customer' }} </span></label>
      </div>
      <div class="split">
          
      </div>
      <div class="cols">
          <div class="split">
              <label style="" class="col-md-4 control-label">----------------<br><span class="sp">{{ 'Authorised' }} </span></label>
          </div>
          <div class="split">
              
          </div>
      </div>
    </div>

    <div class="footer">
      <h1></h1>
      <p>{{ $setting->getCompany->copyright }}</p>
    </div>
  </body>
</html>

resources/views/admin/purchase/view.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Voucher Order Slip</title>
        <!-- <link rel="stylesheet" href="{{ asset('public/admin/css/font-awesome.min.css') }} " type="text/css" /> -->
        <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    </head>
    <body class="light_bg" data-spy="scroll" data-target="#bs-example-navbar-collapse-1" data-offset="80" data-scroll-animation="true">
        <div class="container main_container">
          <div class="content_inner_bg row m0 ">
            <section class="about_person_area pad team_img " id="about">
              <div class="container">
                <div class="row">
                    <div class="col-md-10">
                        <div class="person_img">
                          <img class="img-profile rounded-circle" width="1000" height="600" src="{{ asset('public/Purchase/'. $imga->file ) }}" alt="No Voucher Found" >
                        </div>
                    </div>
                    </div>
                </div>
            </section>
        </div>
      </div>
    </body>
</html>