routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	$item = App\Setting::first();
    return view('admin.login',compact('item'));
});

Route::get('signup', function () {
    return view('admin.login');
});

Route::get('index', function () {
	$slider= view('frontend.slider');
	$video= view('frontend.video');
	$main= view('frontend.main');
    return view('frontend.index',compact('slider','video','main'));
});

Route::get('join-us', function () {
    return view('frontend.login');
});

Route::get('sign-in', function () {
    return view('frontend.register');
});


Auth::routes();
Route::middleware(['auth'])->group(function () {
Route::get('home', 'BackendViewController@index')->name('home');
Route::resource('menu', 'MenuController');
Route::resource('role', 'RoleController');
Route::resource('setting', 'SettingController');
// Route::resource('media', 'MediaController');
Route::resource('user', 'UserController');
Route::resource('permission', 'PermissionController');
Route::get('get-permission', 'PermissionController@permission')->name('get-permission');
Route::resource('currency', 'CurrencyController');
Route::resource('company', 'CompanyController');
Route::resource('customer', 'CustomerController');
Route::resource('supplier', 'SupplierController');
Route::resource('bank', 'BankController');
Route::resource('tree', 'TreeController');
Route::get('list', 'TreeController@list');
Route::get('category-tree-view',['uses'=>'CategoryController@manageCategory'])->name('category-tree-view');
Route::post('add-category',['as'=>'add.category','uses'=>'CategoryController@addCategory']);
Route::resource('ledger', 'LedgerController');
Route::resource('purchase', 'PurchaseController');
Route::get('purch-pdf/{purch_id}', 'PurchaseController@pdf');
Route::resource('payment', 'PaymentController');
Route::resource('payment_type', 'PaymentTypeController');
Route::resource('invoice', 'InvoiceController');
Route::resource('receive', 'ReceiveVoucherController');
Route::resource('journal', 'JournalController');
//Route For the Report
Route::get('report', 'ReportController@report')->name('report');
Route::get('receive_paym', 'ReceivePaymentController@index')->name('receive_paym');
Route::post('receive_paym_post', 'ReceivePaymentController@store')->name('receive_paym_post');
Route::get('bank_book', 'BankController@report')->name('bank_book');
Route::post('bank_book_post', 'BankController@bankReport')->name('bank_book_post');
Route::get('group_index', 'GroupSummaryController@index')->name('group_index');
Route::post('group_post', 'GroupSummaryController@groupPost')->name('group_post');
Route::get('day_book_index', 'DayBookController@index')->name('day_book_index');
Route::post('day_book_post', 'DayBookController@store')->name('day_book_post');
Route::get('balance', 'BalanceController@index')->name('balance');
Route::post('balance_post', 'BalanceController@store')->name('balance_post');
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','user_type','phone',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Auth;
use Db;
use Redirect;
class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.user.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/user/create.blade.php
@extends('admin.pages.dashboard')
@section('content')


<div class="wrapper-md">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading font-bold">
                <div class="row">
                    <div class="col-md-10">
                        <p class="m-n font-thin h3">Company Details</p>
                    </div>
                    <div class="col-md-2">


                    </div>
                </div>
            </div>


            @if(Session::has('success'))

            <div class="alert alert-success" role="alert">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <strong>Success!</strong>{{ Session::get('success') }}!
          </div>

          @endif
          <div class="panel-body">
            <div class="col-md-12 ">
                <form class="bs-example form-horizontal" action="{{ route('user.store') }}" method="post"
                enctype="multipart/form-data">

                {{ csrf_field() }}

                 <input type="hidden" name="_method" value="PUT" />

                <div class="form-group">

                    <div class="col-md-6">
                        <label for="title" class="col-sm-4 col-form-label">{{ 'Company Name' }} <span style="color:red;">*</span></label>
                        <div class="col-sm-8">
                            <input class="form-control" name="company_name"  type="text"   required>

                        </div>

                    </div>
                    <div class="col-md-6">
                        <label for="title" class="col-sm-4 col-form-label">{{ 'Header Title' }} <span style="color:red;">*</span></label>
                        <div class="col-sm-8">
                            <input class="form-control"  name="header_title"   type="text"   required>

                        </div>
                    </div>

                </div>


                <div class="form-group">

                    <div class="col-md-6">
                        <label for="title" class="col-sm-4 col-form-label">{{ 'Company Address' }} <span style="color:red;">*</span></label>
                        <div class="col-sm-8">
                            <input class="form-control" name="company_address"  type="text"   required>

                        </div>

                    </div>
                    <div class="col-md-6">
                        <label for="title" class="col-sm-4 col-form-label">{{ 'Company Phone' }} <span style="color:red;">*</span></label>
                        <div class="col-sm-8">
                            <input class="form-control"  name="company_phone"   type="text"   required>

                        </div>
                    </div>

                </div>



                <div class="form-group">

                    <div class="col-md-6">
                        <label for="title" class="col-sm-4 col-form-label">{{ 'Company Email' }} <span style="color:red;">*</span></label>
                        <div class="col-sm-8">
                            <input class="form-control" name="company_email"   type="text"   required>

                        </div>

                    </div>
                    <div class="col-md-6">
                        <label for="title" class="col-sm-4 col-form-label">{{ 'Copyright' }} <span style="color:red;">*</span></label>
                        <div class="col-sm-8">
                            <input class="form-control"   name="copyright"   type="text"   required>

                        </div>
                    </div>

                </div>

                

                <div class="form-group">

                    <div class="col-md-6">
                        <label for="title" class="col-sm-4 col-form-label">{{ 'Company Logo' }} <span style="color:red;">*</span></label>

                        <div class="col-sm-8">

                            <input class="form-control"   name="company_logo"   type="file"   >

                        </div>
                    </div>

                </div>






                <div class="col-md-12">
                    <hr>
                    <div class="form-group" style="float:right;">
                        <div class="text-center">
                            <input class="btn btn-primary" type="submit" value="Submit ">
                        </div>
                    </div>
                </div>

            </form>
        </div>
    </div>
</div>
</div>
</div>
@endsection

resources/views/admin/user/index.blade.php
    
    @extends('admin.pages.dashboard')
     @section('content')
     <style type="text/css">
     	.fa{
     		font-size: 14px;
     	}
     </style>
      <div class="wrapper-md">
        <div class="panel panel-default">


<div class="row" style="margin-top:10px;">
    <div class="col-md-6 col-md-offset-3 col-xs-12">
        @if (session('success'))
            <div class="alert alert-success text-center">
                <b>{{ session('success') }}</b>
            </div>

        @endif
    </div>
</div>


            <div class="panel-heading">
                <div class="row">
                    <div class="col-md-10">
                        <p class="m-n font-thin h3">All Category</p>
                    </div>
                    <div class="col-md-2">

                          <a href="{{ route('user.create') }}" class="btn btn-primary btn-sm"><i
                                        class="fa fa-plus"></i>&nbsp;Add New </a>

                    </div>
                </div>
            </div>
  
            <div class="panel-body">
                <table id="pattern-type-data" class="table table-bordered">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Name</th>
                        <th>Status</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>

    
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    @endsection